version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
    groups:
      all-deps:
        patterns:
          - "*"
      all-security:
        patterns:
          - "*"
        applies-to: "security-updates"
